services:

  app:

    build: .

    container_name: flask-app

    working_dir: /app/backend  

    ports:
      - "5000:5000"

    environment:

      DB_HOST: postgres
      DB_NAME: flaskdb
      DB_USER: postgres
      DB_PASSWORD: password

      PYTHONPATH: /app/backend  

    depends_on:
      - postgres
