version: "3"

services:

  web:
    build: .
    container_name: python-app
    ports:
      - "5000:5000"
    depends_on:
      - postgres


  postgres:
    image: postgres:15
    container_name: postgres-db

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: projectdb

    ports:
      - "5432:5432"
